export const LLM_GATEWAY_ERROR_CODE_PROFILE_NOT_FOUND =
  "LLM_GATEWAY_PROFILE_NOT_FOUND";
export const LLM_GATEWAY_ERROR_CODE_API_BASE_REQUIRED =
  "LLM_GATEWAY_API_BASE_REQUIRED";
export const LLM_GATEWAY_ERROR_CODE_MODEL_REQUIRED = "LLM_GATEWAY_MODEL_REQUIRED";
export const LLM_GATEWAY_ERROR_CODE_NOTHING_TO_TEST =
  "LLM_GATEWAY_NOTHING_TO_TEST";
export const LLM_GATEWAY_ERROR_CODE_EMBEDDING_MODEL_REQUIRED =
  "LLM_GATEWAY_EMBEDDING_MODEL_REQUIRED";
export const LLM_GATEWAY_ERROR_CODE_RERANK_QUERY_REQUIRED =
  "LLM_GATEWAY_RERANK_QUERY_REQUIRED";
export const LLM_GATEWAY_ERROR_CODE_RERANK_DOCUMENTS_REQUIRED =
  "LLM_GATEWAY_RERANK_DOCUMENTS_REQUIRED";
export const LLM_GATEWAY_ERROR_CODE_RERANK_MODEL_REQUIRED =
  "LLM_GATEWAY_RERANK_MODEL_REQUIRED";
export const LLM_GATEWAY_ERROR_CODE_INVALID_EMBEDDING_RESPONSE =
  "LLM_GATEWAY_INVALID_EMBEDDING_RESPONSE";
export const LLM_GATEWAY_ERROR_CODE_INVALID_RERANK_RESPONSE =
  "LLM_GATEWAY_INVALID_RERANK_RESPONSE";
export const LLM_GATEWAY_ERROR_CODE_RERANK_TEST_FAILED =
  "LLM_GATEWAY_RERANK_TEST_FAILED";
export const LLM_GATEWAY_ERROR_CODE_REQUEST_FAILED =
  "LLM_GATEWAY_REQUEST_FAILED";
export const LLM_GATEWAY_ERROR_CODE_UNAVAILABLE = "LLM_GATEWAY_UNAVAILABLE";
