import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "jsdom",
    setupFiles: ["./test/setup.ts"],
    include: ["**/*.test.{ts,tsx}"],
    css: false,
    restoreMocks: true,
    clearMocks: true,
    env: {
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:4000/api",
      NEXT_PUBLIC_GRAPHQL_APQ_ENABLED: "true",
    },
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      reportsDirectory: "./coverage",
      include: [
        "app/(auth)/login/page.tsx",
        "app/(app)/admin/ops/news-sources/news-sources-content.tsx",
        "components/settings/email-settings-panel.tsx",
        "app/(app)/components/page-container.tsx",
        "app/(app)/components/nav-mode.ts",
        "app/(app)/components/action-rail-routing.ts",
        "app/(app)/components/navigation-model.ts",
        "app/(app)/components/top-nav-density.ts",
        // FE-批3：URL 状态与数据边界原语（FE-01 / DataStateBoundary）
        "lib/url-state-codec.ts",
        "hooks/use-url-state.ts",
        "components/data-state-boundary.tsx",
        // FE-批3：Alert Center 领域模块（FE-03 include 扩充）
        "app/(app)/alerts/alert-center.tsx",
        "app/(app)/alerts/alert-center-url-state.ts",
        "app/(app)/alerts/alert-center-actions.ts",
        "app/(app)/alerts/alert-center-data-state.tsx",
        "app/(app)/alerts/alert-center-filters.tsx",
        "app/(app)/alerts/alert-center-summary.tsx",
        "app/(app)/alerts/alert-center-list-model.ts",
        "app/(app)/alerts/alert-event-controllers.ts",
        "app/(app)/alerts/alert-event-detail-model.ts",
        "app/(app)/alerts/hooks/use-alert-event-detail.ts",
        "app/(app)/alerts/hooks/use-alert-event-batch.ts",
        "app/(app)/alerts/hooks/use-alert-center-charts.ts",
        "app/(app)/alerts/alert-event-detail.tsx",
        "app/(app)/alerts/alert-event-overview-tab.tsx",
        "app/(app)/alerts/alert-event-evidence-tab.tsx",
        "app/(app)/alerts/alert-event-replay-tab.tsx",
        "app/(app)/alerts/alert-event-feedback-tab.tsx",
        "app/(app)/alerts/alert-event-deliveries-tab.tsx",
        "app/(app)/alerts/alert-event-list.tsx",
        "app/(app)/alerts/alert-event-list-toolbar.tsx",
        "app/(app)/alerts/alert-event-row.tsx",
        "app/(app)/alerts/hooks/use-alert-center-url-state.ts",
        "app/(app)/alerts/hooks/use-alert-events-feed.ts",
        "app/(app)/alerts/hooks/use-alert-event-status-actions.ts",
        "app/(app)/alerts/hooks/use-alert-event-selection.ts",
        "app/(app)/alerts/hooks/use-alert-event-virtualization.ts",
        "app/(app)/alerts/alert-events-virtualization.ts",
        "app/(app)/alerts/alert-chart-options.ts",
        "app/(app)/alerts/evidence-utils.tsx",
        "app/(app)/alerts/economic-anomaly-evidence.tsx",
        "app/(app)/alerts/entity-sentiment-evidence.tsx",
        "app/(app)/alerts/entity-association-evidence.tsx",
        "app/(app)/alerts/realtime-signal-evidence.tsx",
        // FE-批4A：War Map 领域模块（URL/查询/运行时/交互/点位/图层/状态）
        "app/(app)/dashboard/charts/war-map/url-state.ts",
        "app/(app)/dashboard/charts/war-map/query-viewport.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-data.ts",
        "app/(app)/dashboard/charts/war-map/war-map-data.ts",
        "app/(app)/dashboard/charts/war-map/war-map-props.ts",
        "app/(app)/dashboard/charts/war-map/war-map.tsx",
        "app/(app)/dashboard/charts/war-map/use-war-map-url-state.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-query-state.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-container.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-runtime.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-interaction.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-points.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-layers.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-overlay-content.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-status-presentation.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-transport-detail.ts",
        "app/(app)/dashboard/charts/war-map/use-war-map-analyze.ts",
        "app/(app)/dashboard/charts/war-map/war-map-selection-model.ts",
        "app/(app)/dashboard/charts/war-map/war-map-point-model.ts",
        "app/(app)/dashboard/charts/war-map/war-map-symbol-layers.ts",
        // FE-批4B：符号系统拆分模块（types/color/svg/icons/legend model/swatch）
        "app/(app)/dashboard/charts/war-map/war-map-symbol-types.ts",
        "app/(app)/dashboard/charts/war-map/war-map-symbol-color.ts",
        "app/(app)/dashboard/charts/war-map/war-map-symbol-svg.ts",
        "app/(app)/dashboard/charts/war-map/war-map-symbol-icons.ts",
        "app/(app)/dashboard/charts/war-map/war-map-legend-model.ts",
        "app/(app)/dashboard/charts/war-map/war-map-legend-swatch.tsx",
        "app/(app)/dashboard/charts/war-map/war-map-static-layers.ts",
        "app/(app)/dashboard/charts/war-map/war-map-static-vector-layers.ts",
        "app/(app)/dashboard/charts/war-map/war-map-ais-layers.ts",
        "app/(app)/dashboard/charts/war-map/war-map-event-layers.ts",
        "app/(app)/dashboard/charts/war-map/war-map-news-layers.ts",
        "app/(app)/dashboard/charts/war-map/war-map-transport-points.ts",
        "app/(app)/dashboard/charts/war-map/war-map-tooltip.ts",
        "app/(app)/dashboard/charts/war-map/war-map-status-model.ts",
        "app/(app)/dashboard/charts/war-map/war-map-flights-status.ts",
        "app/(app)/dashboard/charts/war-map/war-map-ais-status.ts",
        "app/(app)/dashboard/charts/war-map/war-map-load-state.ts",
        "app/(app)/dashboard/charts/war-map/war-map-format.ts",
        "app/(app)/dashboard/charts/war-map/war-map-map-surface.tsx",
        "app/(app)/dashboard/charts/war-map/war-map-overlay-panels.tsx",
        "app/(app)/dashboard/charts/war-map/war-map-view-controls.tsx",
      ],
      exclude: ["**/*.test.{ts,tsx}", "**/graphql/generated.ts"],
      thresholds: {
        lines: 35,
        functions: 3,
        statements: 35,
        branches: 30,
      },
    },
  },
  resolve: {
    alias: {
      "@/components": path.resolve(__dirname, "components"),
      "@/app": path.resolve(__dirname, "app"),
      "@/lib": path.resolve(__dirname, "lib"),
      "@/graphql": path.resolve(__dirname, "graphql"),
      "@/hooks": path.resolve(__dirname, "hooks"),
      "@/store": path.resolve(__dirname, "store"),
      "@/test": path.resolve(__dirname, "test"),
    },
  },
  esbuild: {
    jsx: "automatic",
  },
});
