model_list:
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: openai/text-embedding-3-small
    litellm_params:
      model: openai/text-embedding-3-small
      api_key: os.environ/OPENAI_API_KEY

  - model_name: anthropic/claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku
      api_key: os.environ/ANTHROPIC_API_KEY
