import { z } from "zod";
export declare const baseEnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    MYSQL_HOST: z.ZodString;
    MYSQL_PORT: z.ZodNumber;
    MYSQL_USER: z.ZodString;
    MYSQL_PASSWORD: z.ZodString;
    MYSQL_DB: z.ZodString;
    MONGO_URI: z.ZodUnion<[z.ZodString, z.ZodString]>;
    REDIS_HOST: z.ZodString;
    REDIS_PORT: z.ZodNumber;
    SMTP_HOST: z.ZodDefault<z.ZodString>;
    SMTP_PORT: z.ZodDefault<z.ZodNumber>;
    SMTP_SECURE: z.ZodDefault<z.ZodBoolean>;
    SMTP_USER: z.ZodString;
    SMTP_PASS: z.ZodString;
    SMTP_FROM: z.ZodOptional<z.ZodString>;
    JWT_SECRET: z.ZodString;
    NEXTAUTH_SECRET: z.ZodString;
    NEXTAUTH_URL: z.ZodString;
    API_BASE_URL: z.ZodString;
    CRAWL4AI_BASE_URL: z.ZodString;
    CRAWL4AI_API_KEY: z.ZodOptional<z.ZodString>;
    CRAWL4AI_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    CRAWL4AI_MAX_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    CRAWL4AI_MAX_RETRIES: z.ZodDefault<z.ZodNumber>;
    CRAWL_MEDIA_FETCH_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    CRAWL_MEDIA_MAX_BYTES: z.ZodDefault<z.ZodNumber>;
    CRAWL_MEDIA_MAX_PER_RESULT: z.ZodDefault<z.ZodNumber>;
    LITELLM_MODEL: z.ZodDefault<z.ZodString>;
    LITELLM_API_BASE: z.ZodDefault<z.ZodString>;
    LITELLM_API_KEY: z.ZodOptional<z.ZodString>;
    LITELLM_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    LITELLM_TEMPERATURE: z.ZodDefault<z.ZodNumber>;
    LITELLM_TOP_P: z.ZodDefault<z.ZodNumber>;
    LITELLM_MAX_OUTPUT_TOKENS: z.ZodDefault<z.ZodNumber>;
    LITELLM_MAX_RETRIES: z.ZodDefault<z.ZodNumber>;
    LITELLM_FALLBACK_MODELS: z.ZodOptional<z.ZodString>;
    LITELLM_REQUESTS_PER_MINUTE: z.ZodDefault<z.ZodNumber>;
    AKSHARE_HTTP_BASE_URL: z.ZodDefault<z.ZodString>;
    AKSHARE_HTTP_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    AKSHARE_HTTP_MAX_RETRIES: z.ZodDefault<z.ZodNumber>;
    AKSHARE_QUEUE_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    NEWS_PIPELINE_CACHE_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    NEWS_PIPELINE_MAX_INPUT_CHARS: z.ZodDefault<z.ZodNumber>;
    NEWS_PIPELINE_CONFIG_PATH: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "production" | "development" | "test";
    MYSQL_HOST: string;
    MYSQL_PORT: number;
    MYSQL_USER: string;
    MYSQL_PASSWORD: string;
    MYSQL_DB: string;
    MONGO_URI: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_SECURE: boolean;
    SMTP_USER: string;
    SMTP_PASS: string;
    JWT_SECRET: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    API_BASE_URL: string;
    CRAWL4AI_BASE_URL: string;
    CRAWL4AI_TIMEOUT_MS: number;
    CRAWL4AI_MAX_CONCURRENCY: number;
    CRAWL4AI_MAX_RETRIES: number;
    CRAWL_MEDIA_FETCH_TIMEOUT_MS: number;
    CRAWL_MEDIA_MAX_BYTES: number;
    CRAWL_MEDIA_MAX_PER_RESULT: number;
    LITELLM_MODEL: string;
    LITELLM_API_BASE: string;
    LITELLM_TIMEOUT_MS: number;
    LITELLM_TEMPERATURE: number;
    LITELLM_TOP_P: number;
    LITELLM_MAX_OUTPUT_TOKENS: number;
    LITELLM_MAX_RETRIES: number;
    LITELLM_REQUESTS_PER_MINUTE: number;
    AKSHARE_HTTP_BASE_URL: string;
    AKSHARE_HTTP_TIMEOUT_MS: number;
    AKSHARE_HTTP_MAX_RETRIES: number;
    AKSHARE_QUEUE_CONCURRENCY: number;
    NEWS_PIPELINE_CACHE_TTL_SECONDS: number;
    NEWS_PIPELINE_MAX_INPUT_CHARS: number;
    NEWS_PIPELINE_CONFIG_PATH: string;
    SMTP_FROM?: string | undefined;
    CRAWL4AI_API_KEY?: string | undefined;
    LITELLM_API_KEY?: string | undefined;
    LITELLM_FALLBACK_MODELS?: string | undefined;
}, {
    MYSQL_HOST: string;
    MYSQL_PORT: number;
    MYSQL_USER: string;
    MYSQL_PASSWORD: string;
    MYSQL_DB: string;
    MONGO_URI: string;
    REDIS_HOST: string;
    REDIS_PORT: number;
    SMTP_USER: string;
    SMTP_PASS: string;
    JWT_SECRET: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    API_BASE_URL: string;
    CRAWL4AI_BASE_URL: string;
    NODE_ENV?: "production" | "development" | "test" | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_SECURE?: boolean | undefined;
    SMTP_FROM?: string | undefined;
    CRAWL4AI_API_KEY?: string | undefined;
    CRAWL4AI_TIMEOUT_MS?: number | undefined;
    CRAWL4AI_MAX_CONCURRENCY?: number | undefined;
    CRAWL4AI_MAX_RETRIES?: number | undefined;
    CRAWL_MEDIA_FETCH_TIMEOUT_MS?: number | undefined;
    CRAWL_MEDIA_MAX_BYTES?: number | undefined;
    CRAWL_MEDIA_MAX_PER_RESULT?: number | undefined;
    LITELLM_MODEL?: string | undefined;
    LITELLM_API_BASE?: string | undefined;
    LITELLM_API_KEY?: string | undefined;
    LITELLM_TIMEOUT_MS?: number | undefined;
    LITELLM_TEMPERATURE?: number | undefined;
    LITELLM_TOP_P?: number | undefined;
    LITELLM_MAX_OUTPUT_TOKENS?: number | undefined;
    LITELLM_MAX_RETRIES?: number | undefined;
    LITELLM_FALLBACK_MODELS?: string | undefined;
    LITELLM_REQUESTS_PER_MINUTE?: number | undefined;
    AKSHARE_HTTP_BASE_URL?: string | undefined;
    AKSHARE_HTTP_TIMEOUT_MS?: number | undefined;
    AKSHARE_HTTP_MAX_RETRIES?: number | undefined;
    AKSHARE_QUEUE_CONCURRENCY?: number | undefined;
    NEWS_PIPELINE_CACHE_TTL_SECONDS?: number | undefined;
    NEWS_PIPELINE_MAX_INPUT_CHARS?: number | undefined;
    NEWS_PIPELINE_CONFIG_PATH?: string | undefined;
}>;
export type BaseEnvSchema = typeof baseEnvSchema;
export type BaseEnv = z.infer<typeof baseEnvSchema>;
export interface LoadEnvOptions {
    dotenvPath?: string;
    overrideProcessEnv?: boolean;
}
export declare function loadAndValidateEnv<TSchema extends z.ZodTypeAny>(schema: TSchema, options?: LoadEnvOptions): z.infer<TSchema>;
//# sourceMappingURL=env.d.ts.map