import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  CORE_PERMISSION_DEFINITIONS,
  DEFAULT_ROLES,
  getCorePermissionDefinition,
  getDefaultRoleDefinition,
  shouldBackfillDefaultDescription,
} from "@modular/config";

import { backfillRbacDefaultDescriptions } from "./rbac-default-description-backfill";

describe("rbac default description backfill", () => {
  it("treats empty and legacy descriptions as safe to replace", () => {
    const usersRead = getCorePermissionDefinition("users.read");
    const adminRole = getDefaultRoleDefinition("admin");

    assert.ok(usersRead);
    assert.ok(adminRole);

    assert.equal(shouldBackfillDefaultDescription(null, usersRead), true);
    assert.equal(
      shouldBackfillDefaultDescription(
        "Autogenerated permission users.read",
        usersRead,
      ),
      true,
    );
    assert.equal(
      shouldBackfillDefaultDescription(
        "Full access across the administrative surface",
        adminRole,
      ),
      true,
    );
    assert.equal(
      shouldBackfillDefaultDescription(usersRead.description, usersRead),
      false,
    );
    assert.equal(
      shouldBackfillDefaultDescription("Custom permission copy", usersRead),
      false,
    );
  });

  it("updates only core permissions and system roles with stale default descriptions", async () => {
    const permissionUpdates: Array<{ id: string; description: string }> = [];
    const roleUpdates: Array<{ id: string; description: string }> = [];

    const client = {
      permission: {
        findMany: async () => [
          {
            id: "perm-users-read",
            name: "users.read",
            description: "Autogenerated permission users.read",
          },
          {
            id: "perm-items-read",
            name: "items.read",
            description: "Custom item read copy",
          },
          {
            id: "perm-analysis-run",
            name: "analysis.run",
            description: null,
          },
        ],
        update: async ({ where, data }: { where: { id: string }; data: { description: string } }) => {
          permissionUpdates.push({ id: where.id, description: data.description });
          return {};
        },
      },
      role: {
        findMany: async () => [
          {
            id: "role-admin-org-a",
            name: "admin",
            description: "Full access across the administrative surface",
            isSystem: true,
          },
          {
            id: "role-manager-org-a",
            name: "manager",
            description: "Custom manager copy",
            isSystem: true,
          },
          {
            id: "role-analyst-org-a",
            name: "analyst",
            description: "",
            isSystem: true,
          },
        ],
        update: async ({ where, data }: { where: { id: string }; data: { description: string } }) => {
          roleUpdates.push({ id: where.id, description: data.description });
          return {};
        },
      },
    };

    const result = await backfillRbacDefaultDescriptions(client);

    assert.equal(result.updatedPermissions, 2);
    assert.equal(result.updatedRoles, 2);
    assert.deepEqual(permissionUpdates, [
      {
        id: "perm-users-read",
        description:
          getCorePermissionDefinition("users.read")?.description ?? "",
      },
      {
        id: "perm-analysis-run",
        description:
          getCorePermissionDefinition("analysis.run")?.description ?? "",
      },
    ]);
    assert.deepEqual(roleUpdates, [
      {
        id: "role-admin-org-a",
        description: getDefaultRoleDefinition("admin")?.description ?? "",
      },
      {
        id: "role-analyst-org-a",
        description: getDefaultRoleDefinition("analyst")?.description ?? "",
      },
    ]);
  });

  it("keeps exported RBAC defaults aligned with their definition catalogs", () => {
    assert.equal(CORE_PERMISSION_DEFINITIONS.length > 0, true);
    assert.equal(DEFAULT_ROLES.length > 0, true);
    assert.ok(
      CORE_PERMISSION_DEFINITIONS.every(
        (definition) => getCorePermissionDefinition(definition.name)?.description,
      ),
    );
    assert.ok(
      DEFAULT_ROLES.every(
        (definition) => getDefaultRoleDefinition(definition.name)?.description,
      ),
    );
  });
});
