import bcrypt from "bcrypt";
import { DEFAULT_ROLES, DEFAULT_USERS, CORE_PERMISSIONS } from "@modular/config";
import { prisma } from "./client";

export interface SeedOptions {
  orgSlug?: string;
}

export const seed = async ({ orgSlug = "acme" }: SeedOptions = {}) => {
  const org = await prisma.org.upsert({
    where: { slug: orgSlug },
    update: {},
    create: {
      name: "Acme Corp",
      slug: orgSlug,
      description: "Seed organization",
      isActive: true
    }
  });

  await Promise.all(
    CORE_PERMISSIONS.map((permission) =>
      prisma.permission.upsert({
        where: { name: permission },
        update: {},
        create: {
          name: permission,
          description: `Autogenerated permission ${permission}`
        }
      })
    )
  );

  for (const roleDef of DEFAULT_ROLES) {
    const role = await prisma.role.upsert({
      where: {
        orgId_name: {
          orgId: org.id,
          name: roleDef.name
        }
      },
      update: {
        description: roleDef.description
      },
      create: {
        name: roleDef.name,
        description: roleDef.description,
        orgId: org.id
      }
    });

    const permissions = await prisma.permission.findMany({
      where: { name: { in: roleDef.permissions } }
    });

    for (const permission of permissions) {
      await prisma.rolePermission.upsert({
        where: {
          roleId_permissionId: {
            roleId: role.id,
            permissionId: permission.id
          }
        },
        update: {},
        create: {
          roleId: role.id,
          permissionId: permission.id
        }
      });
    }
  }

  for (const userDef of DEFAULT_USERS) {
    const passwordHash = await bcrypt.hash(userDef.password, 10);
    const user = await prisma.user.upsert({
      where: { email: userDef.email },
      update: {
        passwordHash,
        firstName: userDef.firstName,
        lastName: userDef.lastName,
        isActive: true
      },
      create: {
        email: userDef.email,
        passwordHash,
        firstName: userDef.firstName,
        lastName: userDef.lastName
      }
    });

    for (const roleName of userDef.roles) {
      const role = await prisma.role.findFirstOrThrow({
        where: { orgId: org.id, name: roleName }
      });
      await prisma.membership.upsert({
        where: {
          userId_orgId: {
            userId: user.id,
            orgId: org.id
          }
        },
        update: {
          roleId: role.id
        },
        create: {
          userId: user.id,
          orgId: org.id,
          roleId: role.id
        }
      });
    }
  }

  const seedOwner = await prisma.user.findUnique({
    where: { email: DEFAULT_USERS[0]?.email }
  });

  // Seed a demo item metadata row
  await prisma.itemMeta.upsert({
    where: { externalId: "item-001" },
    update: {
      name: "Sample Item",
      status: "active"
    },
    create: {
      orgId: org.id,
      externalId: "item-001",
      name: "Sample Item",
      status: "active",
      mongoRef: "rawitem-001"
    }
  });

  if (seedOwner) {
    await prisma.crawlTask.upsert({
      where: { id: "seed-crawl-task" },
      update: {
        targetUrl: "https://news.ycombinator.com/",
        status: "pending"
      },
      create: {
        id: "seed-crawl-task",
        orgId: org.id,
        createdById: seedOwner.id,
        targetUrl: "https://news.ycombinator.com/",
        displayName: "HN Headlines",
        status: "pending",
        concurrency: 2,
        keywords: ["ai", "security"],
        config: {
          scanFullPage: true,
          adjustViewportToContent: true,
          scrollDelayMs: 200,
          enableUndetectedBrowser: true,
          enableStealthMode: true,
          simulateUser: true,
          overrideNavigator: true
        },
        lastServerMemoryMb: 420.5,
        lastPeakMemoryMb: 950.2,
        lastMemoryEfficiency: 78.4
        },
        timeRangeFrom: new Date(Date.now() - 1000 * 60 * 60 * 24),
        timeRangeTo: new Date(),
        runCount: 0
      }
    });
  }

  return org;
};

if (require.main === module) {
  seed()
    .then((org) => {
      console.log("Seed data ready for org", org.slug);
      return prisma.$disconnect();
    })
    .catch(async (error) => {
      console.error(error);
      await prisma.$disconnect();
      process.exit(1);
    });
}
