import { CORE_PERMISSIONS, DEFAULT_ROLES, DEFAULT_USERS } from "@modular/config";
import bcrypt from "bcrypt";
import dayjs from "dayjs";

import { prisma } from "./client";

export interface SeedOptions {
  orgSlug?: string;
}

export const seed = async ({ orgSlug = "acme" }: SeedOptions = {}) => {
  const org = await prisma.org.upsert({
    where: { slug: orgSlug },
    update: {},
    create: {
      name: "Acme Corp",
      slug: orgSlug,
      description: "Seed organization",
      isActive: true
    }
  });

  await Promise.all(
    CORE_PERMISSIONS.map((permission) =>
      prisma.permission.upsert({
        where: { name: permission },
        update: {},
        create: {
          name: permission,
          description: `Autogenerated permission ${permission}`
        }
      })
    )
  );

  for (const roleDef of DEFAULT_ROLES) {
    const role = await prisma.role.upsert({
      where: {
        orgId_name: {
          orgId: org.id,
          name: roleDef.name
        }
      },
      update: {
        description: roleDef.description,
        isSystem: roleDef.isSystem ?? false
      },
      create: {
        name: roleDef.name,
        description: roleDef.description,
        orgId: org.id,
        isSystem: roleDef.isSystem ?? false
      }
    });

    const permissions = await prisma.permission.findMany({
      where: { name: { in: roleDef.permissions } }
    });

    for (const permission of permissions) {
      await prisma.rolePermission.upsert({
        where: {
          roleId_permissionId: {
            roleId: role.id,
            permissionId: permission.id
          }
        },
        update: {},
        create: {
          roleId: role.id,
          permissionId: permission.id
        }
      });
    }
  }

  for (const userDef of DEFAULT_USERS) {
    const passwordHash = await bcrypt.hash(userDef.password, 10);
    const user = await prisma.user.upsert({
      where: { email: userDef.email },
      update: {
        passwordHash,
        firstName: userDef.firstName,
        lastName: userDef.lastName,
        isActive: true
      },
      create: {
        email: userDef.email,
        passwordHash,
        firstName: userDef.firstName,
        lastName: userDef.lastName
      }
    });

    for (const roleName of userDef.roles) {
      const role = await prisma.role.findFirstOrThrow({
        where: { orgId: org.id, name: roleName }
      });
      await prisma.membership.upsert({
        where: {
          userId_orgId: {
            userId: user.id,
            orgId: org.id
          }
        },
        update: {
          roleId: role.id
        },
        create: {
          userId: user.id,
          orgId: org.id,
          roleId: role.id
        }
      });
    }
  }

  const seedOwner = await prisma.user.findUnique({
    where: { email: DEFAULT_USERS[0]?.email }
  });

  // Seed a demo item metadata row
  await prisma.itemMeta.upsert({
    where: {
      orgId_externalId: {
        orgId: org.id,
        externalId: "item-001"
      }
    },
    update: {
      name: "Sample Item",
      status: "active"
    },
    create: {
      orgId: org.id,
      externalId: "item-001",
      name: "Sample Item",
      status: "active",
      mongoRef: "rawitem-001"
    }
  });

  if (seedOwner) {
    await prisma.crawlTask.upsert({
      where: { id: "seed-crawl-task" },
      update: {
        targetUrl: "https://news.ycombinator.com/",
        status: "pending"
      },
      create: {
        id: "seed-crawl-task",
        orgId: org.id,
        createdById: seedOwner.id,
        targetUrl: "https://news.ycombinator.com/",
        displayName: "HN Headlines",
        status: "pending",
        concurrency: 2,
        keywords: ["ai", "security"],
        config: {
          scanFullPage: true,
          adjustViewportToContent: true,
          scrollDelayMs: 200,
          enableUndetectedBrowser: true,
          enableStealthMode: true,
          simulateUser: true,
          overrideNavigator: true
        },
        lastServerMemoryMb: 420.5,
        lastPeakMemoryMb: 950.2,
        lastMemoryEfficiency: 78.4,
        timeRangeFrom: new Date(Date.now() - 1000 * 60 * 60 * 24),
        timeRangeTo: new Date(),
        runCount: 0
      }
    });

    // --- Seed Dashboard Metrics (Real Data Simulation) ---
    const metrics = [
      { slug: "global-conflict-index", name: "Global Conflict Index", base: 65, vol: 5 },
      { slug: "market-sentiment", name: "Market Sentiment", base: 50, vol: 10 },
      { slug: "resource-scarcity", name: "Resource Scarcity", base: 60, vol: 3 },
      { slug: "supply-chain-stability", name: "Supply Chain Stability", base: 85, vol: 2 }
    ];

    for (const m of metrics) {
      // 1. Create/Update Item
      const item = await prisma.economicDataItem.upsert({
        where: { slug: m.slug },
        update: {},
        create: {
          slug: m.slug,
          displayName: m.name,
          sourceFunction: "mock",
          sourceEndpoint: "mock",
          valueType: "index",
          defaultFrequency: "daily"
        }
      });

      // 2. Generate History (last 90 days)
      const points = [];
      let value = m.base;
      for (let i = 90; i >= 0; i--) {
        const date = dayjs().subtract(i, "day").toDate();
        // Random walk
        value += (Math.random() - 0.5) * m.vol; 
        value = Math.max(0, Math.min(100, value)); // Clamp 0-100

        points.push({
          itemId: item.id,
          recordedAt: date,
          dataType: "index" as const,
          value: value,
          sourceField: "value"
        });
      }

      // Bulk upsert logic (using createMany is faster for seeds but skips duplicates, loop is safer for updates)
      // For seed, we just wipe and recreate or ignore duplicates?
      // Simple loop with upsert for safety
      for (const p of points) {
        await prisma.economicDataPoint.upsert({
          where: {
            itemId_recordedAt_sourceField: {
              itemId: p.itemId,
              recordedAt: p.recordedAt,
              sourceField: p.sourceField
            }
          },
          update: { value: p.value },
          create: p
        });
      }

      // 3. Create Alert Rule & Events (for Drill-down Map)
      const rule = await prisma.alertRule.upsert({
        where: { id: `rule-${m.slug}` },
        update: {},
        create: {
          id: `rule-${m.slug}`,
          orgId: org.id,
          name: `${m.name} Monitor`,
          metricSlug: m.slug,
          operator: "gt",
          thresholdValue: 80,
          createdById: seedOwner.id,
          status: "active"
        }
      });
      
      // Seed some events with Geo Context
      const countries = ["China", "USA", "Russia", "Germany", "Iran"];
      for (let i = 0; i < 5; i++) {
        const country = countries[Math.floor(Math.random() * countries.length)];
        await prisma.alertEvent.create({
          data: {
            ruleId: rule.id,
            triggeredAt: dayjs().subtract(Math.random() * 7, 'day').toDate(),
            metricValue: 80 + Math.random() * 20,
            severity: Math.random() > 0.5 ? "high" : "medium",
            status: "pending",
            message: `${m.name} spike detected in ${country} region due to volatility.`,
            context: {
              country: country,
              region: "Global",
              notes: "Auto-generated by seed"
            }
          }
        });
      }
    }
  }

  return org;
};

if (require.main === module) {
  seed()
    .then((org) => {
      console.log("Seed data ready for org", org.slug);
      return prisma.$disconnect();
    })
    .catch(async (error) => {
      console.error(error);
      await prisma.$disconnect();
      process.exit(1);
    });
}
