package dashboardwarmap

// aliasEntries / localeAliasEntries 与 packages/utils/src/geo.ts 的手写别名同序。
// 中文国名的其余条目来自 CLDR（golang.org/x/text），对应 Node Intl.DisplayNames。
var aliasEntries = [][2]string{
	{"America", "USA"},
	{"Bolivia", "BOL"},
	{"Bosnia", "BIH"},
	{"Burma", "MMR"},
	{"Cabo Verde", "CPV"},
	{"Cape Verde", "CPV"},
	{"Czech Republic", "CZE"},
	{"Czechia", "CZE"},
	{"DRC", "COD"},
	{"Democratic Republic of the Congo", "COD"},
	{"Congo-Kinshasa", "COD"},
	{"Republic of the Congo", "COG"},
	{"Congo-Brazzaville", "COG"},
	{"Eswatini", "SWZ"},
	{"Iran", "IRN"},
	{"Ivory Coast", "CIV"},
	{"Korea", "KOR"},
	{"Laos", "LAO"},
	{"Macedonia", "MKD"},
	{"North Macedonia", "MKD"},
	{"North Korea", "PRK"},
	{"Palestine", "PSE"},
	{"Russia", "RUS"},
	{"South Korea", "KOR"},
	{"Syria", "SYR"},
	{"Tanzania", "TZA"},
	{"Turkey", "TUR"},
	{"UK", "GBR"},
	{"U.K.", "GBR"},
	{"UAE", "ARE"},
	{"United Kingdom", "GBR"},
	{"United Arab Emirates", "ARE"},
	{"United States", "USA"},
	{"United States of America", "USA"},
	{"US", "USA"},
	{"USA", "USA"},
	{"U.S.", "USA"},
	{"East Timor", "TLS"},
	{"Viet Nam", "VNM"},
	{"Venezuela", "VEN"},
	{"Vietnam", "VNM"},
}

var localeAliasEntries = [][2]string{
	{"中国", "CHN"},
	{"中國", "CHN"},
	{"中国台湾", "TWN"},
	{"中国台灣", "TWN"},
	{"中國台湾", "TWN"},
	{"中國台灣", "TWN"},
	{"中國臺灣", "TWN"},
	{"中国台北", "TWN"},
	{"中國台北", "TWN"},
	{"中國臺北", "TWN"},
	{"台湾", "TWN"},
	{"台灣", "TWN"},
	{"美国", "USA"},
	{"美國", "USA"},
	{"英国", "GBR"},
	{"英國", "GBR"},
	{"俄罗斯", "RUS"},
	{"俄羅斯", "RUS"},
	{"乌克兰", "UKR"},
	{"烏克蘭", "UKR"},
	{"日本", "JPN"},
	{"韩国", "KOR"},
	{"韓國", "KOR"},
	{"朝鲜", "PRK"},
	{"朝鮮", "PRK"},
	{"以色列", "ISR"},
	{"巴勒斯坦", "PSE"},
	{"伊朗", "IRN"},
	{"土耳其", "TUR"},
	{"叙利亚", "SYR"},
	{"敘利亞", "SYR"},
	{"中华人民共和国", "CHN"},
	{"中華人民共和國", "CHN"},
	{"东帝汶", "TLS"},
	{"東帝汶", "TLS"},
}
