import fs from 'node:fs';
import path from 'node:path';

import type { TFunction } from 'i18next';
import { describe, expect, it } from 'vitest';

import {
  formatAccessPermissionOptionLabel,
  formatAccessRoleOptionLabel,
  getCorePermissionTranslationEntries,
  getSystemRoleTranslationEntries,
  localizeAccessPermission,
  localizeAccessRole,
} from '../lib/access-settings-rbac-i18n';

const webRoot = path.resolve(__dirname, '..');

const readLocale = (name: 'en' | 'zh') =>
  JSON.parse(
    fs.readFileSync(path.resolve(webRoot, `lib/locales/${name}.json`), 'utf8'),
  ) as Record<string, unknown>;

const getDeepValue = (
  value: Record<string, unknown>,
  pathKey: string,
): unknown =>
  pathKey.split('.').reduce<unknown>((current, segment) => {
    if (!current || typeof current !== 'object') {
      return undefined;
    }

    return (current as Record<string, unknown>)[segment];
  }, value);

const interpolate = (template: string, options?: Record<string, unknown>) =>
  template.replace(/\{\{\s*([^}\s]+)\s*\}\}/g, (_match, key) => {
    const value = options?.[key];
    return value === undefined || value === null ? '' : String(value);
  });

const createTranslator = (translations: Record<string, unknown>) =>
  ((key: string, options?: Record<string, unknown>) => {
    const raw = getDeepValue(translations, key);
    if (typeof raw === 'string') {
      return interpolate(raw, options);
    }
    if (typeof options?.defaultValue === 'string') {
      return interpolate(options.defaultValue, options);
    }
    return key;
  }) as TFunction;

describe('access settings RBAC localization', () => {
  const en = readLocale('en');
  const zh = readLocale('zh');
  const enTranslator = createTranslator(en);
  const zhTranslator = createTranslator(zh);

  it('localizes known system roles in zh-CN and preserves raw identifiers in option labels', () => {
    const localizedRole = localizeAccessRole(
      {
        name: 'admin',
        description: 'Full access across the administrative surface',
        isSystem: true,
      },
      zhTranslator,
    );

    expect(localizedRole.label).toBe('工作区管理员');
    expect(localizedRole.description).toBe(
      '管理工作区访问控制、系统设置、数据操作以及审核流程。',
    );
    expect(formatAccessRoleOptionLabel(
      {
        name: 'admin',
        description: 'Full access across the administrative surface',
        isSystem: true,
      },
      zhTranslator,
    )).toBe('工作区管理员 (admin)');
  });

  it('localizes core permissions in zh-CN and shows the raw code in option labels', () => {
    const localizedPermission = localizeAccessPermission(
      {
        name: 'users.read',
        description: 'Autogenerated permission users.read',
      },
      zhTranslator,
    );

    expect(localizedPermission.label).toBe('查看用户');
    expect(localizedPermission.description).toBe(
      '查看工作区成员、资料和访问分配。',
    );
    expect(
      formatAccessPermissionOptionLabel(
        {
          name: 'users.read',
          description: 'Autogenerated permission users.read',
        },
        zhTranslator,
      ),
    ).toBe('查看用户 (users.read)');
  });

  it('uses user-facing English labels in en-US instead of raw system role names', () => {
    const localizedRole = localizeAccessRole(
      {
        name: 'manager',
        description: 'Manage teams and items but limited system configuration',
        isSystem: true,
      },
      enTranslator,
    );

    expect(localizedRole.label).toBe('Manager');
    expect(localizedRole.description).toBe(
      'Manage members, content, and operational workflows without full system settings access.',
    );
  });

  it('preserves custom roles and unknown permissions as raw values', () => {
    expect(
      localizeAccessRole(
        {
          name: 'Ops Review',
          description: 'Custom review path',
          isSystem: false,
        },
        zhTranslator,
      ),
    ).toEqual({
      label: 'Ops Review',
      description: 'Custom review path',
      rawLabel: 'Ops Review',
      rawDescription: 'Custom review path',
      localized: false,
    });

    expect(
      localizeAccessPermission(
        {
          name: 'custom.manage',
          description: 'Custom permission',
        },
        zhTranslator,
      ),
    ).toEqual({
      label: 'custom.manage',
      description: 'Custom permission',
      rawLabel: 'custom.manage',
      rawDescription: 'Custom permission',
      localized: false,
    });
  });

  it('covers system role and core permission translation keys in both locale files', () => {
    for (const role of getSystemRoleTranslationEntries()) {
      expect(getDeepValue(en, `settings.rbac.roles.${role.key}.label`)).toBeTypeOf(
        'string',
      );
      expect(
        getDeepValue(en, `settings.rbac.roles.${role.key}.description`),
      ).toBeTypeOf('string');
      expect(getDeepValue(zh, `settings.rbac.roles.${role.key}.label`)).toBeTypeOf(
        'string',
      );
      expect(
        getDeepValue(zh, `settings.rbac.roles.${role.key}.description`),
      ).toBeTypeOf('string');
    }

    for (const permission of getCorePermissionTranslationEntries()) {
      expect(
        getDeepValue(en, `settings.rbac.permissions.${permission.key}.label`),
      ).toBeTypeOf('string');
      expect(
        getDeepValue(en, `settings.rbac.permissions.${permission.key}.description`),
      ).toBeTypeOf('string');
      expect(
        getDeepValue(zh, `settings.rbac.permissions.${permission.key}.label`),
      ).toBeTypeOf('string');
      expect(
        getDeepValue(zh, `settings.rbac.permissions.${permission.key}.description`),
      ).toBeTypeOf('string');
    }
  });
});
