import type { EconomicDataFrequency } from "@prisma/client";
import { EconomicDataValueType } from "@prisma/client";

import { AKSHARE_DATA_DEFINITIONS } from "./akshare.definitions";
import type {
  FinancialDataItemDefinition,
  FinancialDataProviderConfig,
  FinancialDataSnapshotMetadata,
} from "./financial-data.types";

const HOURLY: EconomicDataFrequency = "hourly";
const DAILY: EconomicDataFrequency = "daily";
const WEEKLY: EconomicDataFrequency = "weekly";

function toAkshareDefinition(
  definition: (typeof AKSHARE_DATA_DEFINITIONS)[number],
): FinancialDataItemDefinition {
  const providerConfig: FinancialDataProviderConfig = {
    kind: "akshare",
    functionName: definition.sourceFunction,
    endpoint: definition.endpoint,
    docUrl: definition.docUrl,
    method: definition.method ?? "GET",
    defaultParams: definition.defaultParams,
    filter: definition.filter,
    parser: definition.parser,
  };

  return {
    id: definition.id,
    slug: definition.slug,
    displayName: definition.displayName,
    description: definition.description,
    categories: definition.categories,
    sourceFunction: definition.sourceFunction,
    endpoint: definition.endpoint,
    docUrl: definition.docUrl,
    valueType: definition.valueType,
    defaultUnit: definition.defaultUnit,
    defaultFrequency: definition.defaultFrequency,
    providerConfig,
    provider: "akshare",
    defaultEnabled: true,
    mainlineRole: "canonical",
    tags: definition.tags,
  };
}

function createFinnhubDefinition(input: {
  id: string;
  slug: string;
  displayName: string;
  description: string;
  symbol: string;
  displaySymbol: string;
  categories: string[];
  mainlineRole: "canonical" | "internal";
  snapshot: FinancialDataSnapshotMetadata;
  tags?: string[];
}): FinancialDataItemDefinition {
  return {
    id: input.id,
    slug: input.slug,
    displayName: input.displayName,
    description: input.description,
    categories: input.categories,
    sourceFunction: "finnhub.quote",
    endpoint: "/quote",
    docUrl: "https://finnhub.io/docs/api/quote",
    valueType: EconomicDataValueType.price,
    defaultUnit: "USD",
    defaultFrequency: HOURLY,
    providerConfig: {
      kind: "finnhub",
      symbol: input.symbol,
      endpoint: "/quote",
      docUrl: "https://finnhub.io/docs/api/quote",
      metric: "quote_price",
      sourceField: "price",
    },
    provider: "finnhub",
    requiresSecret: "finnhubApiKey",
    defaultEnabled: false,
    mainlineRole: input.mainlineRole,
    snapshot: input.snapshot,
    tags: input.tags ?? [],
  };
}

function createFredDefinition(input: {
  id: string;
  slug: string;
  displayName: string;
  description: string;
  categories: string[];
  sourceFunction: string;
  seriesId: string;
  metric: "latest" | "yoy" | "delta" | "percentOfMax";
  defaultFrequency: EconomicDataFrequency;
  defaultUnit?: string;
  valueType?: EconomicDataValueType;
  mainlineRole?: "canonical" | "derived";
  snapshot?: FinancialDataSnapshotMetadata;
  transform?: "identity" | "millionsToTrillions";
  lookback?: number;
  precision?: number;
  tags?: string[];
}): FinancialDataItemDefinition {
  return {
    id: input.id,
    slug: input.slug,
    displayName: input.displayName,
    description: input.description,
    categories: input.categories,
    sourceFunction: input.sourceFunction,
    endpoint: "/series/observations",
    docUrl: "https://fred.stlouisfed.org/docs/api/fred/series_observations.html",
    valueType: input.valueType ?? EconomicDataValueType.quantity,
    defaultUnit: input.defaultUnit,
    defaultFrequency: input.defaultFrequency,
    providerConfig: {
      kind: "fred",
      seriesId: input.seriesId,
      endpoint: "/series/observations",
      docUrl: "https://fred.stlouisfed.org/docs/api/fred/series_observations.html",
      metric: input.metric,
      sourceField: "value",
      lookback: input.lookback,
      precision: input.precision,
      transform: input.transform,
    },
    provider: "fred",
    requiresSecret: "fredApiKey",
    defaultEnabled: false,
    mainlineRole: input.mainlineRole ?? "canonical",
    snapshot: input.snapshot,
    tags: input.tags ?? [],
  };
}

const FINNHUB_DEFINITIONS: FinancialDataItemDefinition[] = [
  createFinnhubDefinition({
    id: "spy-sp500-proxy-internal",
    slug: "spy_sp500_proxy_internal",
    displayName: "S&P 500 Proxy ETF",
    description: "Finnhub quote for SPY, used as an internal S&P 500 proxy in the financial mainline.",
    symbol: "SPY",
    displaySymbol: "^GSPC",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "internal",
    snapshot: {
      group: "markets",
      bucket: "indices",
      symbol: "^GSPC",
      name: "S&P 500",
      order: 10,
    },
    tags: ["proxy", "us-equity", "index"],
  }),
  createFinnhubDefinition({
    id: "qqq-nasdaq-proxy-internal",
    slug: "qqq_nasdaq_proxy_internal",
    displayName: "NASDAQ Proxy ETF",
    description: "Finnhub quote for QQQ, used as an internal NASDAQ proxy in the financial mainline.",
    symbol: "QQQ",
    displaySymbol: "^IXIC",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "internal",
    snapshot: {
      group: "markets",
      bucket: "indices",
      symbol: "^IXIC",
      name: "NASDAQ",
      order: 20,
    },
    tags: ["proxy", "us-equity", "index"],
  }),
  createFinnhubDefinition({
    id: "dia-dow-proxy-internal",
    slug: "dia_dow_proxy_internal",
    displayName: "Dow Jones Proxy ETF",
    description: "Finnhub quote for DIA, used as an internal Dow Jones proxy in the financial mainline.",
    symbol: "DIA",
    displaySymbol: "^DJI",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "internal",
    snapshot: {
      group: "markets",
      bucket: "indices",
      symbol: "^DJI",
      name: "Dow Jones",
      order: 30,
    },
    tags: ["proxy", "us-equity", "index"],
  }),
  createFinnhubDefinition({
    id: "iwm-russell2000-proxy-internal",
    slug: "iwm_russell2000_proxy_internal",
    displayName: "Russell 2000 Proxy ETF",
    description: "Finnhub quote for IWM, used as an internal Russell 2000 proxy in the financial mainline.",
    symbol: "IWM",
    displaySymbol: "^RUT",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "internal",
    snapshot: {
      group: "markets",
      bucket: "indices",
      symbol: "^RUT",
      name: "Russell 2000",
      order: 40,
    },
    tags: ["proxy", "us-equity", "index"],
  }),
  createFinnhubDefinition({
    id: "xlk-sector-etf",
    slug: "xlk_sector_etf",
    displayName: "Technology Sector ETF",
    description: "Finnhub quote for XLK technology sector ETF.",
    symbol: "XLK",
    displaySymbol: "XLK",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLK", name: "Tech", order: 10 },
    tags: ["sector", "technology", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xlf-sector-etf",
    slug: "xlf_sector_etf",
    displayName: "Financials Sector ETF",
    description: "Finnhub quote for XLF financial sector ETF.",
    symbol: "XLF",
    displaySymbol: "XLF",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLF", name: "Finance", order: 20 },
    tags: ["sector", "financials", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xle-sector-etf",
    slug: "xle_sector_etf",
    displayName: "Energy Sector ETF",
    description: "Finnhub quote for XLE energy sector ETF.",
    symbol: "XLE",
    displaySymbol: "XLE",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLE", name: "Energy", order: 30 },
    tags: ["sector", "energy", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xlv-sector-etf",
    slug: "xlv_sector_etf",
    displayName: "Health Care Sector ETF",
    description: "Finnhub quote for XLV health care sector ETF.",
    symbol: "XLV",
    displaySymbol: "XLV",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLV", name: "Health", order: 40 },
    tags: ["sector", "health-care", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xly-sector-etf",
    slug: "xly_sector_etf",
    displayName: "Consumer Discretionary Sector ETF",
    description: "Finnhub quote for XLY consumer discretionary sector ETF.",
    symbol: "XLY",
    displaySymbol: "XLY",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLY", name: "Consumer", order: 50 },
    tags: ["sector", "consumer", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xli-sector-etf",
    slug: "xli_sector_etf",
    displayName: "Industrials Sector ETF",
    description: "Finnhub quote for XLI industrials sector ETF.",
    symbol: "XLI",
    displaySymbol: "XLI",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLI", name: "Industrial", order: 60 },
    tags: ["sector", "industrials", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xlp-sector-etf",
    slug: "xlp_sector_etf",
    displayName: "Consumer Staples Sector ETF",
    description: "Finnhub quote for XLP consumer staples sector ETF.",
    symbol: "XLP",
    displaySymbol: "XLP",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLP", name: "Staples", order: 70 },
    tags: ["sector", "consumer-staples", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xlu-sector-etf",
    slug: "xlu_sector_etf",
    displayName: "Utilities Sector ETF",
    description: "Finnhub quote for XLU utilities sector ETF.",
    symbol: "XLU",
    displaySymbol: "XLU",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLU", name: "Utilities", order: 80 },
    tags: ["sector", "utilities", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xlb-sector-etf",
    slug: "xlb_sector_etf",
    displayName: "Materials Sector ETF",
    description: "Finnhub quote for XLB materials sector ETF.",
    symbol: "XLB",
    displaySymbol: "XLB",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLB", name: "Materials", order: 90 },
    tags: ["sector", "materials", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xlre-sector-etf",
    slug: "xlre_sector_etf",
    displayName: "Real Estate Sector ETF",
    description: "Finnhub quote for XLRE real estate sector ETF.",
    symbol: "XLRE",
    displaySymbol: "XLRE",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLRE", name: "Real Est", order: 100 },
    tags: ["sector", "real-estate", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "xlc-sector-etf",
    slug: "xlc_sector_etf",
    displayName: "Communication Services Sector ETF",
    description: "Finnhub quote for XLC communication services sector ETF.",
    symbol: "XLC",
    displaySymbol: "XLC",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "XLC", name: "Comms", order: 110 },
    tags: ["sector", "communication-services", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "smh-sector-etf",
    slug: "smh_sector_etf",
    displayName: "Semiconductor Sector ETF",
    description: "Finnhub quote for SMH semiconductor sector ETF.",
    symbol: "SMH",
    displaySymbol: "SMH",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "sectors", symbol: "SMH", name: "Semis", order: 120 },
    tags: ["sector", "semiconductors", "us-equity"],
  }),
  createFinnhubDefinition({
    id: "vixy-proxy-etf",
    slug: "vixy_proxy_etf",
    displayName: "VIX Proxy ETF",
    description: "Finnhub quote for VIXY, used as a VIX proxy in the financial mainline.",
    symbol: "VIXY",
    displaySymbol: "^VIX",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "commodities", symbol: "^VIX", name: "VIX", order: 10 },
    tags: ["volatility", "proxy", "risk"],
  }),
  createFinnhubDefinition({
    id: "gld-proxy-etf",
    slug: "gld_proxy_etf",
    displayName: "Gold Proxy ETF",
    description: "Finnhub quote for GLD, used as a gold proxy in the financial mainline.",
    symbol: "GLD",
    displaySymbol: "GC=F",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "commodities", symbol: "GC=F", name: "Gold", order: 20 },
    tags: ["commodity", "gold", "proxy"],
  }),
  createFinnhubDefinition({
    id: "uso-proxy-etf",
    slug: "uso_proxy_etf",
    displayName: "Crude Oil Proxy ETF",
    description: "Finnhub quote for USO, used as a crude oil proxy in the financial mainline.",
    symbol: "USO",
    displaySymbol: "CL=F",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "commodities", symbol: "CL=F", name: "Crude Oil", order: 30 },
    tags: ["commodity", "oil", "proxy"],
  }),
  createFinnhubDefinition({
    id: "ung-proxy-etf",
    slug: "ung_proxy_etf",
    displayName: "Natural Gas Proxy ETF",
    description: "Finnhub quote for UNG, used as a natural gas proxy in the financial mainline.",
    symbol: "UNG",
    displaySymbol: "NG=F",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "commodities", symbol: "NG=F", name: "Natural Gas", order: 40 },
    tags: ["commodity", "natural-gas", "proxy"],
  }),
  createFinnhubDefinition({
    id: "slv-proxy-etf",
    slug: "slv_proxy_etf",
    displayName: "Silver Proxy ETF",
    description: "Finnhub quote for SLV, used as a silver proxy in the financial mainline.",
    symbol: "SLV",
    displaySymbol: "SI=F",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "commodities", symbol: "SI=F", name: "Silver", order: 50 },
    tags: ["commodity", "silver", "proxy"],
  }),
  createFinnhubDefinition({
    id: "cper-proxy-etf",
    slug: "cper_proxy_etf",
    displayName: "Copper Proxy ETF",
    description: "Finnhub quote for CPER, used as a copper proxy in the financial mainline.",
    symbol: "CPER",
    displaySymbol: "HG=F",
    categories: ["key-monitor", "economic-alert"],
    mainlineRole: "canonical",
    snapshot: { group: "markets", bucket: "commodities", symbol: "HG=F", name: "Copper", order: 60 },
    tags: ["commodity", "copper", "proxy"],
  }),
];

const FRED_DEFINITIONS: FinancialDataItemDefinition[] = [
  createFredDefinition({
    id: "us-fed-funds-rate",
    slug: "us_fed_funds_rate",
    displayName: "US Fed Funds Rate",
    description: "FRED FEDFUNDS series, stored as the latest observed policy rate.",
    categories: ["macro-us", "economic-alert", "key-monitor"],
    sourceFunction: "fred.series.latest",
    seriesId: "FEDFUNDS",
    metric: "latest",
    defaultUnit: "%",
    valueType: EconomicDataValueType.percent,
    defaultFrequency: DAILY,
    snapshot: {
      group: "fed",
      bucket: "indicators",
      symbol: "FEDFUNDS",
      name: "Fed Funds Rate",
      order: 10,
    },
    tags: ["rates", "fed", "macro-us"],
  }),
  createFredDefinition({
    id: "us-cpi-yoy-fred",
    slug: "us_cpi_yoy_fred",
    displayName: "US CPI YoY (FRED)",
    description: "Derived year-over-year CPI inflation from the FRED CPIAUCSL series.",
    categories: ["macro-us", "economic-alert"],
    sourceFunction: "fred.series.yoy",
    seriesId: "CPIAUCSL",
    metric: "yoy",
    defaultUnit: "%",
    valueType: EconomicDataValueType.percent,
    defaultFrequency: WEEKLY,
    mainlineRole: "derived",
    snapshot: {
      group: "fed",
      bucket: "indicators",
      symbol: "CPIAUCSL",
      name: "CPI Inflation",
      order: 20,
    },
    lookback: 14,
    tags: ["inflation", "cpi", "macro-us"],
  }),
  createFredDefinition({
    id: "us-10y-treasury-yield-fred",
    slug: "us_10y_treasury_yield_fred",
    displayName: "US 10Y Treasury Yield (FRED)",
    description: "FRED DGS10 series, stored as the latest observed US 10Y Treasury yield.",
    categories: ["macro-us", "economic-alert", "key-monitor"],
    sourceFunction: "fred.series.latest",
    seriesId: "DGS10",
    metric: "latest",
    defaultUnit: "%",
    valueType: EconomicDataValueType.percent,
    defaultFrequency: DAILY,
    snapshot: {
      group: "fed",
      bucket: "indicators",
      symbol: "DGS10",
      name: "10Y Treasury",
      order: 30,
    },
    tags: ["rates", "treasury", "macro-us"],
  }),
  createFredDefinition({
    id: "fed-balance-sheet-total-assets",
    slug: "fed_balance_sheet_total_assets",
    displayName: "Fed Balance Sheet Total Assets",
    description: "FRED WALCL series converted to trillions of USD for the financial mainline.",
    categories: ["macro-us", "economic-alert", "key-monitor"],
    sourceFunction: "fred.series.total_assets",
    seriesId: "WALCL",
    metric: "latest",
    defaultUnit: "T USD",
    valueType: EconomicDataValueType.quantity,
    defaultFrequency: WEEKLY,
    transform: "millionsToTrillions",
    lookback: 260,
    tags: ["fed", "balance-sheet", "macro-us"],
  }),
  createFredDefinition({
    id: "fed-balance-sheet-change",
    slug: "fed_balance_sheet_change",
    displayName: "Fed Balance Sheet Weekly Change",
    description: "Derived weekly change in the FRED WALCL series, expressed in trillions of USD.",
    categories: ["macro-us", "economic-alert"],
    sourceFunction: "fred.series.delta",
    seriesId: "WALCL",
    metric: "delta",
    defaultUnit: "T USD",
    valueType: EconomicDataValueType.quantity,
    defaultFrequency: WEEKLY,
    mainlineRole: "derived",
    transform: "millionsToTrillions",
    lookback: 260,
    tags: ["fed", "balance-sheet", "macro-us"],
  }),
  createFredDefinition({
    id: "fed-money-printer-percent-of-max",
    slug: "fed_money_printer_percent_of_max",
    displayName: "Fed Money Printer Percent Of Max",
    description: "Derived percent-of-peak value from the FRED WALCL series.",
    categories: ["macro-us", "economic-alert"],
    sourceFunction: "fred.series.percent_of_max",
    seriesId: "WALCL",
    metric: "percentOfMax",
    defaultUnit: "%",
    valueType: EconomicDataValueType.percent,
    defaultFrequency: WEEKLY,
    mainlineRole: "derived",
    lookback: 260,
    tags: ["fed", "balance-sheet", "macro-us"],
  }),
];

export const ECONOMIC_DATA_SOURCE_DEFINITIONS: FinancialDataItemDefinition[] = [
  ...AKSHARE_DATA_DEFINITIONS.map(toAkshareDefinition),
  ...FRED_DEFINITIONS,
  ...FINNHUB_DEFINITIONS,
];

export const ECONOMIC_DATA_SOURCE_DEFINITION_MAP = new Map(
  ECONOMIC_DATA_SOURCE_DEFINITIONS.map((definition) => [definition.slug, definition]),
);

export const FINANCIAL_DATA_DEFINITIONS = ECONOMIC_DATA_SOURCE_DEFINITIONS;
export const FINANCIAL_DATA_DEFINITION_MAP = ECONOMIC_DATA_SOURCE_DEFINITION_MAP;
