const CHUNK_PUBLIC_PATH = "server/app/page.js";
const runtime = require("../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/7a35e_next_4398be._.js");
runtime.loadChunk("server/chunks/ssr/50e31_@auth_core_8bbee2._.js");
runtime.loadChunk("server/chunks/ssr/5c0e8_jose_dist_webapi_713fd4._.js");
runtime.loadChunk("server/chunks/ssr/6ac78_oauth4webapi_build_index_8747f9.js");
runtime.loadChunk("server/chunks/ssr/ec2d6_zod_v3_a349db._.js");
runtime.loadChunk("server/chunks/ssr/08b5e__pnpm_f7fd9b._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__76cffc._.js");
runtime.getOrInstantiateRuntimeModule("[project]/apps/web/.next-internal/server/app/page/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/.pnpm/next@15.0.0-canary.45_@babel+core@7.28.5_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { COMPONENT_0 => \"[project]/apps/web/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", COMPONENT_1 => \"[project]/node_modules/.pnpm/next@15.0.0-canary.45_@babel+core@7.28.5_react-dom@19.2.3_react@19.2.3__react@19.2.3/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", COMPONENT_2 => \"[project]/apps/web/app/page.tsx [app-rsc] (ecmascript, Next.js server component)\", METADATA_3 => \"[project]/apps/web/app/icon.svg.mjs { IMAGE => \\\"[project]/apps/web/app/icon.svg [app-rsc] (static)\\\" } [app-rsc] (structured image object, ecmascript)\" } [app-rsc] (ecmascript) <facade>", CHUNK_PUBLIC_PATH).exports;
