export interface CorePermissionDefinition {
  name: string;
  description: string;
  legacyDescriptions?: readonly string[];
}

const CORE_PERMISSION_DESCRIPTION_MAP = {
  "org.read": "Review organization details and membership scope.",
  "org.write": "Create, update, and administer organization records.",
  "settings.manage":
    "Access and change administrative settings across the workspace.",
  "users.read": "Review workspace members, profiles, and access assignments.",
  "users.write":
    "Update user access, activation state, and related admin actions.",
  "roles.read": "Inspect system and custom role definitions.",
  "roles.write":
    "Create or update role bundles and their permission assignments.",
  "permissions.read": "Inspect the available permission catalog.",
  "permissions.write": "Change permission definitions and policy mappings.",
  "items.read": "Read ingested items and related content records.",
  "items.write": "Create, edit, or remove content items.",
  "dashboards.read": "Open dashboards and read workspace metrics.",
  "dashboards.write": "Create, edit, and publish dashboards.",
  "knowledgegraph.review":
    "Review low-confidence graph relations and moderation queues.",
  "alerts.read": "Read alert rules, states, and recent triggers.",
  "alerts.manage": "Create, edit, and operate alerting workflows.",
  "analysis.read": "Read saved analysis outputs and related results.",
  "analysis.run": "Launch analysis jobs and refresh derived results.",
  "assistant.read": "Open assistant features and review prior runs.",
  "assistant.run": "Send prompts and execute assistant workflows.",
  "queue.manage": "Operate queue state, retries, and worker-facing controls.",
  "crawl.read": "Review crawl tasks, status, and output history.",
  "crawl.write": "Create, edit, or run crawl tasks.",
  "economicdata.read": "Read economic series, snapshots, and derived views.",
  "economicdata.manage":
    "Refresh, configure, and administer economic data pipelines.",
  "akshare.fetch": "Trigger AKShare-backed market and macro data collection.",
} as const;

export type CorePermission = keyof typeof CORE_PERMISSION_DESCRIPTION_MAP;

export const CORE_PERMISSION_DEFINITIONS: CorePermissionDefinition[] =
  Object.entries(CORE_PERMISSION_DESCRIPTION_MAP).map(([name, description]) => ({
    name: name as CorePermission,
    description,
    legacyDescriptions: [`Autogenerated permission ${name}`],
  }));

export const CORE_PERMISSIONS: CorePermission[] = CORE_PERMISSION_DEFINITIONS.map(
  (definition) => definition.name as CorePermission,
);

export interface DefaultRoleDefinition {
  name: string;
  description: string;
  permissions: readonly CorePermission[];
  isSystem?: boolean;
  legacyDescriptions?: readonly string[];
}

export const DEFAULT_ROLES: DefaultRoleDefinition[] = [
  {
    name: "admin",
    description:
      "Manage workspace access, system settings, data operations, and review flows.",
    permissions: [...CORE_PERMISSIONS],
    isSystem: true,
    legacyDescriptions: ["Full access across the administrative surface"],
  },
  {
    name: "manager",
    description:
      "Manage members, content, and operational workflows without full system settings access.",
    permissions: [
      "org.read",
      "users.read",
      "users.write",
      "roles.read",
      "permissions.read",
      "items.read",
      "items.write",
      "dashboards.read",
      "dashboards.write",
      "alerts.read",
      "alerts.manage",
      "analysis.read",
      "analysis.run",
      "assistant.read",
      "assistant.run",
      "queue.manage",
      "crawl.read",
      "crawl.write",
      "economicdata.read",
      "akshare.fetch",
    ],
    isSystem: true,
    legacyDescriptions: [
      "Manage teams and items but limited system configuration",
    ],
  },
  {
    name: "analyst",
    description:
      "View workspace data, dashboards, alerts, and analysis tools without write access.",
    permissions: [
      "org.read",
      "users.read",
      "roles.read",
      "items.read",
      "dashboards.read",
      "alerts.read",
      "analysis.read",
      "assistant.read",
      "crawl.read",
      "economicdata.read",
    ],
    isSystem: true,
    legacyDescriptions: ["Read-only access to organizational and item data"],
  },
];

const corePermissionDefinitionMap = new Map(
  CORE_PERMISSION_DEFINITIONS.map((definition) => [definition.name, definition]),
);

const defaultRoleDefinitionMap = new Map(
  DEFAULT_ROLES.map((definition) => [definition.name, definition]),
);

export interface DefaultDescriptionDefinition {
  description: string;
  legacyDescriptions?: readonly string[];
}

export function getCorePermissionDefinition(
  name: string,
): CorePermissionDefinition | undefined {
  return corePermissionDefinitionMap.get(name as CorePermission);
}

export function getDefaultRoleDefinition(
  name: string,
): DefaultRoleDefinition | undefined {
  return defaultRoleDefinitionMap.get(name);
}

export function shouldBackfillDefaultDescription(
  currentDescription: string | null | undefined,
  definition: DefaultDescriptionDefinition,
): boolean {
  const normalizedCurrent =
    typeof currentDescription === "string" ? currentDescription.trim() : "";

  if (!normalizedCurrent) {
    return true;
  }

  if (normalizedCurrent === definition.description) {
    return false;
  }

  return (definition.legacyDescriptions ?? []).includes(normalizedCurrent);
}
