import {
  CrawlStrategyWorkflowNodeType,
  type CrawlStrategyWorkflowNodeSchema,
} from './crawl-strategy.types';

const COMMON_PATTERN_ARRAY = {
  type: 'array',
  items: { type: 'string' },
  default: [],
};

export const CRAWL_STRATEGY_NODE_SCHEMAS: CrawlStrategyWorkflowNodeSchema[] = [
  {
    type: CrawlStrategyWorkflowNodeType.SeedDiscovery,
    displayName: 'Seed Discovery',
    category: 'discovery',
    description: 'Resolve the first batch of URLs from sitemap, RSS, or an explicit seed URL.',
    defaultLabel: 'Seed Discovery',
    supportsTrialRun: true,
    defaults: {
      mode: 'sitemap',
      seedUrl: '',
      maxUrls: 40,
      domain: '',
      pattern: '',
      feedUrl: '',
    },
    configSchema: {
      type: 'object',
      properties: {
        mode: {
          type: 'string',
          enum: ['sitemap', 'rss'],
          default: 'sitemap',
        },
        seedUrl: { type: 'string', default: '' },
        domain: { type: 'string', default: '' },
        pattern: { type: 'string', default: '' },
        feedUrl: { type: 'string', default: '' },
        maxUrls: { type: 'number', minimum: 1, maximum: 200, default: 40 },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.ListDiscovery,
    displayName: 'List Discovery',
    category: 'discovery',
    description: 'Discover article candidates from a list hub or archive page.',
    defaultLabel: 'List Discovery',
    supportsTrialRun: true,
    defaults: {
      listUrl: '',
      domain: '',
      pattern: '',
      maxUrls: 60,
      listMaxPages: 6,
      listPageConcurrency: 2,
      followPagination: true,
    },
    configSchema: {
      type: 'object',
      properties: {
        listUrl: { type: 'string', default: '' },
        domain: { type: 'string', default: '' },
        pattern: { type: 'string', default: '' },
        maxUrls: { type: 'number', minimum: 1, maximum: 500, default: 60 },
        listMaxPages: { type: 'number', minimum: 1, maximum: 20, default: 6 },
        listPageConcurrency: {
          type: 'number',
          minimum: 1,
          maximum: 6,
          default: 2,
        },
        followPagination: { type: 'boolean', default: true },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.DeepDiscovery,
    displayName: 'Deep Discovery',
    category: 'discovery',
    description: 'Run Crawl4AI deep crawl and collect article candidates.',
    defaultLabel: 'Deep Discovery',
    supportsTrialRun: true,
    defaults: {
      seedUrl: '',
      domain: '',
      pattern: '',
      query: '',
      maxUrls: 60,
      deep: {
        maxPages: 80,
        maxDepth: 2,
        timeBudgetSeconds: 60,
        pageConcurrency: 2,
        scoreThreshold: 0.2,
        candidatePoolSize: 120,
        headFetchTopK: 40,
        preferPathDate: true,
        enableSecondaryHubs: true,
        ignoreRobotsTxt: false,
      },
    },
    configSchema: {
      type: 'object',
      properties: {
        seedUrl: { type: 'string', default: '' },
        domain: { type: 'string', default: '' },
        pattern: { type: 'string', default: '' },
        query: { type: 'string', default: '' },
        maxUrls: { type: 'number', minimum: 1, maximum: 500, default: 60 },
        deep: {
          type: 'object',
          properties: {
            maxPages: { type: 'number', default: 80 },
            maxDepth: { type: 'number', default: 2 },
            timeBudgetSeconds: { type: 'number', default: 60 },
            pageConcurrency: { type: 'number', default: 2 },
            scoreThreshold: { type: 'number', default: 0.2 },
            candidatePoolSize: { type: 'number', default: 120 },
            headFetchTopK: { type: 'number', default: 40 },
            preferPathDate: { type: 'boolean', default: true },
            enableSecondaryHubs: { type: 'boolean', default: true },
            ignoreRobotsTxt: { type: 'boolean', default: false },
          },
        },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.UrlFilter,
    displayName: 'URL Filter',
    category: 'filter',
    description: 'Apply include/exclude patterns, blocked domains, and keyword denies before scoring.',
    defaultLabel: 'URL Filter',
    supportsTrialRun: true,
    defaults: {
      includePatterns: [],
      excludePatterns: [],
      blockedDomains: [],
      allowedHosts: [],
      denyKeywords: [],
    },
    configSchema: {
      type: 'object',
      properties: {
        includePatterns: COMMON_PATTERN_ARRAY,
        excludePatterns: COMMON_PATTERN_ARRAY,
        blockedDomains: COMMON_PATTERN_ARRAY,
        allowedHosts: COMMON_PATTERN_ARRAY,
        denyKeywords: COMMON_PATTERN_ARRAY,
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.ContentFilter,
    displayName: 'Content Filter',
    category: 'filter',
    description: 'Fetch content metadata and reject candidates with weak content signals.',
    defaultLabel: 'Content Filter',
    supportsTrialRun: true,
    defaults: {
      query: '',
      minRelevanceScore: 0.2,
      requireTitle: true,
      titleIncludes: [],
      descriptionIncludes: [],
      maxFetch: 20,
    },
    configSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', default: '' },
        minRelevanceScore: { type: 'number', default: 0.2 },
        requireTitle: { type: 'boolean', default: true },
        titleIncludes: COMMON_PATTERN_ARRAY,
        descriptionIncludes: COMMON_PATTERN_ARRAY,
        maxFetch: { type: 'number', minimum: 1, maximum: 100, default: 20 },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.PageTypeClassifier,
    displayName: 'Page Type Classifier',
    category: 'scorer',
    description: 'Combine URL and signal heuristics to classify article/list/category/home.',
    defaultLabel: 'Page Type',
    supportsTrialRun: true,
    defaults: {},
    configSchema: { type: 'object', properties: {} },
  },
  {
    type: CrawlStrategyWorkflowNodeType.UrlScorer,
    displayName: 'URL Scorer',
    category: 'scorer',
    description: 'Compute crawl priority based on URL structure, keywords, and page type.',
    defaultLabel: 'URL Score',
    supportsTrialRun: true,
    defaults: {
      keywordBoosts: [],
    },
    configSchema: {
      type: 'object',
      properties: {
        keywordBoosts: COMMON_PATTERN_ARRAY,
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.FreshnessScorer,
    displayName: 'Freshness Scorer',
    category: 'scorer',
    description: 'Estimate freshness from URL date signals using configurable windows.',
    defaultLabel: 'Freshness',
    supportsTrialRun: true,
    defaults: {
      recentHours: 24,
      weekHours: 168,
      monthHours: 720,
    },
    configSchema: {
      type: 'object',
      properties: {
        recentHours: { type: 'number', default: 24 },
        weekHours: { type: 'number', default: 168 },
        monthHours: { type: 'number', default: 720 },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.Branch,
    displayName: 'Branch / Condition',
    category: 'control',
    description: 'Split candidates by a condition such as page type or score threshold.',
    defaultLabel: 'Branch',
    supportsTrialRun: true,
    defaults: {
      field: 'pageType',
      operator: 'equals',
      value: 'article',
    },
    configSchema: {
      type: 'object',
      properties: {
        field: {
          type: 'string',
          enum: ['pageType', 'score', 'freshnessScore', 'relevanceScore'],
          default: 'pageType',
        },
        operator: {
          type: 'string',
          enum: ['equals', 'gte', 'lte', 'contains'],
          default: 'equals',
        },
        value: { type: 'string', default: 'article' },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.BudgetControl,
    displayName: 'Budget Control',
    category: 'control',
    description: 'Apply explicit crawl budget and quality threshold before persistence.',
    defaultLabel: 'Budget Control',
    supportsTrialRun: true,
    defaults: {
      keepTopK: 20,
      minScore: 0,
      maxPages: 60,
      maxDepth: 3,
    },
    configSchema: {
      type: 'object',
      properties: {
        keepTopK: { type: 'number', minimum: 1, maximum: 500, default: 20 },
        minScore: { type: 'number', minimum: -5, maximum: 5, default: 0 },
        maxPages: { type: 'number', minimum: 1, maximum: 500, default: 60 },
        maxDepth: { type: 'number', minimum: 1, maximum: 8, default: 3 },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.FallbackStrategy,
    displayName: 'Fallback Strategy',
    category: 'control',
    description: 'Explicitly re-run a secondary discovery strategy when the current branch is empty.',
    defaultLabel: 'Fallback',
    supportsTrialRun: true,
    defaults: {
      activateWhen: 'empty',
      mode: 'list',
      seedUrl: '',
      domain: '',
      pattern: '',
      maxUrls: 20,
    },
    configSchema: {
      type: 'object',
      properties: {
        activateWhen: {
          type: 'string',
          enum: ['empty', 'always'],
          default: 'empty',
        },
        mode: {
          type: 'string',
          enum: ['list', 'deep', 'rss', 'sitemap'],
          default: 'list',
        },
        seedUrl: { type: 'string', default: '' },
        domain: { type: 'string', default: '' },
        pattern: { type: 'string', default: '' },
        query: { type: 'string', default: '' },
        maxUrls: { type: 'number', minimum: 1, maximum: 200, default: 20 },
      },
    },
  },
  {
    type: CrawlStrategyWorkflowNodeType.PersistResult,
    displayName: 'Persist Result',
    category: 'output',
    description: 'Finalize the selected candidate set that will be applied or inspected.',
    defaultLabel: 'Persist Result',
    supportsTrialRun: true,
    defaults: {
      selectTopK: 20,
    },
    configSchema: {
      type: 'object',
      properties: {
        selectTopK: { type: 'number', minimum: 1, maximum: 500, default: 20 },
      },
    },
  },
];

export function getCrawlStrategyNodeSchema(type: string) {
  return CRAWL_STRATEGY_NODE_SCHEMAS.find((entry) => entry.type === type) ?? null;
}
