package publicportal

// 默认来源名单与复合公共后缀，逐项对应
// apps/api/src/modules/news-events/news-event-source-classifier.ts。
// init 时再走与 Nest 相同的 normalize，避免手抄时漏掉规范化。

var rawAuthoritativeDomains = []string{
	"reuters.com",
	"bloomberg.com",
	"apnews.com",
	"afp.com",
	"bbc.com",
	"bbc.co.uk",
	"ft.com",
	"financialtimes.com",
	"wsj.com",
	"thetimes.co.uk",
	"telegraph.co.uk",
	"independent.co.uk",
	"skynews.com",
	"news.sky.com",
	"nytimes.com",
	"washingtonpost.com",
	"theguardian.com",
	"economist.com",
	"theatlantic.com",
	"foreignpolicy.com",
	"foreignaffairs.com",
	"hbr.org",
	"cnbc.com",
	"forbes.com",
	"marketwatch.com",
	"barrons.com",
	"foxbusiness.com",
	"wsj.net",
	"yahoo.com",
	"finance.yahoo.com",
	"axios.com",
	"politico.com",
	"npr.org",
	"cnn.com",
	"foxnews.com",
	"abcnews.go.com",
	"abcnews.com",
	"cbsnews.com",
	"nbcnews.com",
	"time.com",
	"newsweek.com",
	"usatoday.com",
	"latimes.com",
	"thehill.com",
	"aljazeera.com",
	"dw.com",
	"france24.com",
	"lemonde.fr",
	"lefigaro.fr",
	"lesechos.fr",
	"liberation.fr",
	"elpais.com",
	"elmundo.es",
	"expansion.com",
	"corriere.it",
	"repubblica.it",
	"ilsole24ore.com",
	"spiegel.de",
	"faz.net",
	"handelsblatt.com",
	"sueddeutsche.de",
	"tagesschau.de",
	"nzz.ch",
	"swissinfo.ch",
	"nikkei.com",
	"asia.nikkei.com",
	"scmp.com",
	"caixin.com",
	"kyodonews.net",
	"jiji.com",
	"asahi.com",
	"mainichi.jp",
	"yomiuri.co.jp",
	"yna.co.kr",
	"koreatimes.co.kr",
	"koreaherald.com",
	"joongang.co.kr",
	"japantimes.co.jp",
	"straitstimes.com",
	"channelnewsasia.com",
	"thejakartapost.com",
	"nzherald.co.nz",
	"stuff.co.nz",
	"1news.co.nz",
	"smh.com.au",
	"theage.com.au",
	"afr.com",
	"abc.net.au",
	"theglobeandmail.com",
	"globalnews.ca",
	"cp24.com",
	"cbc.ca",
	"ctvnews.ca",
	"i24news.tv",
	"haaretz.com",
	"jpost.com",
	"thenationalnews.com",
	"arabnews.com",
	"timesofindia.indiatimes.com",
	"economictimes.indiatimes.com",
	"hindustantimes.com",
	"thehindu.com",
	"indianexpress.com",
	"moneycontrol.com",
	"newyorker.com",
	"propublica.org",
	"semafor.com",
	"fortune.com",
	"businessinsider.com",
	"federalreserve.gov",
	"ecb.europa.eu",
	"imf.org",
	"worldbank.org",
	"oecd.org",
	"bis.org",
	"sec.gov",
	"cftc.gov",
	"treasury.gov",
	"who.int",
	"un.org",
	"boe.co.uk",
	"bankofengland.co.uk",
	"bankofcanada.ca",
	"rba.gov.au",
	"boj.or.jp",
	"fca.org.uk",
	"esma.europa.eu",
	"europa.eu",
	"upi.com",
	"dpa.com",
	"ansa.it",
	"efe.com",
	"euronews.com",
	"bnnbloomberg.ca",
	"morningstar.com",
	"spglobal.com",
	"moodys.com",
	"fitchratings.com",
	"argusmedia.com",
	"icis.com",
	"nhk.or.jp",
	"xinhuanet.com",
	"people.com.cn",
	"chinadaily.com.cn",
	"cgtn.com",
	"rferl.org",
	"voanews.com",
	"aa.com.tr",
	"cdc.gov",
	"usgs.gov",
	"noaa.gov",
	"energy.gov",
	"nasa.gov",
}

var rawAuthoritativeLabels = []string{
	"reuters",
	"bloomberg",
	"associated press",
	"ap news",
	"agence france-presse",
	"afp",
	"bbc",
	"financial times",
	"wall street journal",
	"the times",
	"the telegraph",
	"the independent",
	"sky news",
	"new york times",
	"washington post",
	"the guardian",
	"the economist",
	"the atlantic",
	"foreign policy",
	"foreign affairs",
	"harvard business review",
	"cnbc",
	"fox business",
	"yahoo finance",
	"marketwatch",
	"barrons",
	"politico",
	"axios",
	"npr",
	"cnn",
	"fox news",
	"abc news",
	"cbs news",
	"nbc news",
	"le monde",
	"le figaro",
	"les echos",
	"liberation",
	"el pais",
	"el mundo",
	"expansion",
	"corriere della sera",
	"la repubblica",
	"il sole 24 ore",
	"der spiegel",
	"frankfurter allgemeine",
	"handelsblatt",
	"suddeutsche zeitung",
	"tagesschau",
	"nzz",
	"swissinfo",
	"nikkei",
	"south china morning post",
	"caixin",
	"kyodo news",
	"jiji press",
	"asahi shimbun",
	"mainichi shimbun",
	"yomiuri shimbun",
	"yonhap",
	"korea times",
	"korea herald",
	"joongang ilbo",
	"the jakarta post",
	"new zealand herald",
	"the age",
	"sydney morning herald",
	"australian financial review",
	"al jazeera",
	"deutsche welle",
	"france 24",
	"cbc news",
	"ctv news",
	"the globe and mail",
	"the jerusalem post",
	"the national",
	"arab news",
	"times of india",
	"the economic times",
	"hindustan times",
	"the hindu",
	"the indian express",
	"straits times",
	"channel news asia",
	"new yorker",
	"propublica",
	"fortune",
	"federal reserve",
	"european central bank",
	"imf",
	"world bank",
	"oecd",
	"bank for international settlements",
	"sec",
	"cftc",
	"u s treasury",
	"who",
	"united nations",
	"bank of england",
	"bank of canada",
	"reserve bank of australia",
	"bank of japan",
	"fca",
	"esma",
	"united press international",
	"upi",
	"deutsche presse agentur",
	"dpa",
	"ansa",
	"efe",
	"euronews",
	"bnn bloomberg",
	"morningstar",
	"s p global",
	"sp global",
	"moody s",
	"moodys",
	"fitch ratings",
	"argus media",
	"icis",
	"nhk",
	"xinhua",
	"people s daily",
	"china daily",
	"cgtn",
	"radio free europe",
	"voice of america",
	"anadolu agency",
	"u s centers for disease control",
	"cdc",
	"u s geological survey",
	"usgs",
	"noaa",
	"u s department of energy",
	"nasa",
}

var rawBlogDomains = []string{
	"substack.com",
	"medium.com",
	"blogspot.com",
	"wordpress.com",
	"ghost.io",
	"github.io",
	"hashnode.dev",
	"dev.to",
	"rumble.com",
	"youtube.com",
	"youtu.be",
	"tiktok.com",
	"twitter.com",
	"x.com",
	"reddit.com",
	"t.me",
	"telegram.me",
	"discord.gg",
	"discord.com",
	"facebook.com",
	"instagram.com",
	"threads.net",
	"weibo.com",
	"wechat.com",
	"patreon.com",
	"onlyfans.com",
	"kick.com",
	"bitchute.com",
	"quora.com",
	"tumblr.com",
	"linktr.ee",
	"mastodon.social",
	"pixelfed.social",
	"zhihu.com",
	"telegra.ph",
	"mirror.xyz",
	"notion.site",
	"bilibili.com",
	"vimeo.com",
	"odysee.com",
	"kuaishou.com",
	"douyin.com",
}

var rawBlogLabels = []string{
	"substack",
	"newsletter",
	"blog",
	"creator",
	"influencer",
	"opinion blog",
	"rumble",
	"youtube",
	"twitter",
	"x",
	"reddit",
	"telegram",
	"tiktok",
	"discord",
	"threads",
	"weibo",
	"wechat",
	"patreon",
	"mastodon",
	"podcast",
	"self media",
	"op ed",
	"commentary",
	"personal blog",
	"creator economy",
	"livestream",
}

var rawCompoundSuffixes = []string{
	"co.uk",
	"org.uk",
	"gov.uk",
	"ac.uk",
	"com.au",
	"net.au",
	"org.au",
	"co.nz",
	"com.br",
	"com.mx",
	"com.tr",
	"com.cn",
	"com.hk",
	"com.tw",
	"com.sg",
	"co.jp",
	"co.kr",
	"co.in",
	"co.id",
	"co.il",
	"com.ar",
	"com.sa",
	"com.ng",
}
